### ISSUE TITLE
Can we add a simple output report of daily totals by coabdis and eic?

### ISSUE THREAD

**Issue by leoand23** [mmb-carb/GATE#10]
Current optional report has the following information:

    Pollutant,Input(tons/day),After Scaling(tons/day),Output(tons/day)
    CO,203.024088505,205.952640106,205.95261218
    NOX,46.7762121745,47.4498776859,47.4329607511
    PM,8.97535783014,9.06677261483,8.84015657139
    SOX,4.55459957208,4.62622380046,4.62809940651
    TOG,28.0708227104,28.3751592588,10.7742550967

It would be nice to have a new kind of csv report by coabdis and eic as either:

    co,basin,district,eic,pol,ems(tpd) (collapsed)

or

    eic,co,basin,district,co,nox,sox,tog,pm,nh3 (expanded)

**Comment by john-science** [comment]
This is looking doable.  Though it will probably have to be by GAI, without the full basin, district breakdown.  Because we don't currently have basin or district in the model.  And those would be confusing to add in for multi-state runs.

**Comment by leoand23** [comment]
I checked the output files, and there seems to be only output for the Area portion of the inventory. In other words, there are no records in the .inputs_total.csv file for the point sources; therefore the totals in the .inputs_total.csv are much smaller than the totals in the .outputs_total.csv
Also, would it be possible to re-order the pollutants in the csv to have the following order: 
co,nox,sox,tog,pm (same order as in a meds file)

**Comment by john-science** [comment]
Ah, yes, I found a typo. Fixing it now.
